#!/usr/bin/env bash

# This script will resolve or create hotfix branches for you. When resolving it
# makes sure that the hotfix is applied to both master and live.

# Usage:
#     git hotfix [--resolve|-r] <hotfix-branch-name>

# If any command fails, script should fail.
set -e

if [[ "$1" == "--resolve" || "$1" == "-r" ]]; then

    start_branch=`git branch | grep \* | tr "*" " "`

    # Resolve an existing hotfix branch in to live and master

    shift
    branch="${1/-hotfix/}-hotfix"

    git checkout -b "copy-$branch" "$branch"
    git rebase --onto master live "copy-$branch"
    git checkout master
    git merge --no-ff "copy-$branch"
    git branch -d "copy-$branch"

    git checkout live
    git merge --no-ff "$branch"
    git branch -d "$branch"

    git checkout "$start_branch"

else

    # Create a new hotfix branch.
    git checkout -b "${1/-hotfix/}-hotfix" live

fi

